version: "3"
services:
  scraper:
    build:
      context: .
      dockerfile: ./src/scraper/Dockerfile
    env_file: ./config/secret.env
    image: angadsharma1016/spotify-downloader-scraper
    ports:
      - 3000:3000
    depends_on:
      - redis

  ytber:
    build:
      context: .
      dockerfile: ./src/ytber/Dockerfile
    env_file: ./config/secret.env
    image: angadsharma1016/spotify-downloader-ytber
      #volumes:
      #- ./music:/root/
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
