version: "3"
services:
  scraper:
    env_file: ./config/secret.env
    image: angadsharma1016/spotify-downloader-scraper:v0.1.5
    ports:
      - 3000:3000
    depends_on:
      - redis

  ytber:
    env_file: ./config/secret.env
    image: angadsharma1016/spotify-downloader-ytber:v0.1.5
    volumes:
      - ./music/:/root/music/
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
