name: Scraper Docker Push

on: 
  release:
    types:
      - created

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spotify-downloader-ytber:${{ env.RELEASE_VERSION }}
          file: ./src/ytber/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
